name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight

jobs:
  flutter-tests:
    name: Analyze/format/test Flutter ${{ matrix.flutter_version }} on ${{ matrix.os }}
    strategy:
      matrix:
        flutter_version: [dev, beta, stable]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.flutter_version }}
      - run: flutter pub get
      - run: flutter format -n --set-exit-if-changed .
      - run: flutter analyze
      - run: flutter test
      - run: cd example && flutter test
